spring.application.name=MS-02-NetflixZuul-APIGATEWAY
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=9797



spring.cloud.gateway.routes[0].id=flipart
spring.cloud.gateway.routes[0].uri=lb://MS-02-ShoppingServiceMS
spring.cloud.gateway.routes[0].predicates[0]=Path=/flipart-api/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1   ##Remove the first path segment (here: fpkt-billing) from the incoming path before forwarding.

#spring.cloud.gateway.routes[1].id=fpkt
#spring.cloud.gateway.routes[1].uri=lb://MS-02-BillingServiceMS
#spring.cloud.gateway.routes[1].predicates[0]=Path=/fpkt-billing/**


spring.cloud.gateway.routes[1].id=fpkt
spring.cloud.gateway.routes[1].uri=lb://MS-02-BillingServiceMS
spring.cloud.gateway.routes[1].predicates[0]=Path=/fpkt-billing/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1  #Remove the first path segment (here: fpkt-billing) from the incoming path before forwarding.


#Links
#1.http://192.168.1.33:9797/flipart-api/ShoppingMS/Shopping 
#2.http://localhost:8761/   -->eureka



#These projects are running on spring  cloud gateway









#zuul.routes.flipart.path=/flipart-api/**
#zuul.routes.fpkt.path=/fpkt-billing/**
#zuul.routes.flipkart.service-id=MS-02-ShoppingServiceMS
#zuul.routes.fpkt.service-id=Billing-service
