spring.application.name=MS-01-ShoppingServiceMS
server.port = 9091
logging.file.name=C:/Downloads/saikumar.log


#zipkin home page
#http://localhost:9411/zipkin/


#executing jar file
#java -jar zipkin-server-2.12.9-exec.jar

#http://localhost:9091/ShoppingMS/Shopping