spring.application.name=MS-02-NetflixZuul-APIGATEWAY
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=9797



spring.cloud.gateway.routes[0].id=flipart
spring.cloud.gateway.routes[0].uri=lb://MS-03-ShoppingServiceMS
spring.cloud.gateway.routes[0].predicates[0]=Path=/flipart-api/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1   
##Remove the first path segment (here: fpkt-billing) from the incoming path before forwarding.


spring.cloud.gateway.routes[1].id=fpkt
spring.cloud.gateway.routes[1].uri=lb://MS-03-BillingServiceMS
spring.cloud.gateway.routes[1].predicates[0]=Path=/fpkt-billing/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1  

#Remove the first path segment (here: fpkt-billing) from the incoming path before forwarding.



logging.file.name = C:/Downloads/Test.log
logging.level.com.example.demo=info










