spring.application.name=MS-03-BillingServiceMS
server.port = 9092
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#it will random instances
eureka.instance.instance-id=${spring.application.name}:${random.value}
